# Site settings
title: Alung on Github
header-img: img/home-bg.jpg
email: syahrul110100@gmail.com
copyright_name: Your/Project/Corporate Name
description: "I'm Here!"
baseurl: "/startbootstrap-clean-blog-jekyll"
url: "http://alung.github.io"
twitter_username: SBootstrap
github_username:  davidtmiller
facebook_username:  IronSummitMedia
email_username:  syahrul110100@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
